### ISSUE TITLE
Sorry

### ISSUE THREAD

**Issue by ahmadzuh12** [Kashish-Sharma/TheNetwork-open#2]

**Comment by Kashish-Sharma** [comment]
Can you please post the error log here?

**Comment by ahmadzuh12** [comment]
sorry,  I can't upload the log now,, but tomorrow I will upload the log

**Comment by ahmadzuh12** [comment]
Thanks you

**Comment by Kashish-Sharma** [comment]
I'm closing this issue. If you have any queries, please open a new one.
